# Generated by Django 3.0 on 2021-06-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20210620_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstudent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='studentphoto'),
        ),
    ]
